### ISSUE TITLE
allow the rest of us greater access to this repository?

### ISSUE THREAD

**Issue by pritikin** [ComplianceCow/CAML#13]
currently we can view but can't manage issues. not sure of the granularity of permissions but Settings | Manage Access and then invite us as collaborators...

**Comment by rajkrishnamurthy** [comment]
max: added you as an admin. Others please send your github handles to max or me.

**Comment by pritikin** [comment]
I’m not seeing that that worked. Perhaps the wrong max? 
Account is ‘pritikin’ and its tied to my ***@***.*** address. 

Could be I’m missing something obvious. (I’m on an iPad for the rest of the week so maybe I’m just being dense) 

- max
