### ISSUE TITLE
Let's create a docs section with a "Design Decisions" document

### ISSUE THREAD

**Issue by JonathanChristopherson** [ComplianceCow/CAML#31]
One thing that helps a code contributor is when the docs have a "Design Decisions" document that can help the contributor understand specific decision points and why they were made.  This also allows the project team to go back and refactor when considerations change.

**Comment by JonathanChristopherson** [comment]
The first things in this Decisions doc should be a description of the discussion 2022/01/14 on "Is there both yaml and code implementing the policy or is there just yaml which is interpreted by a service which then builds the query to the metrics server?"  Decision in the conversation was that yaml is read by interpreter to compute the metric by building a query to measures service because that way we lessen drift between source of truth and implementation, and to aid in abstraction of policy in yaml from implementation of query building.

Collecting the measures is pure code.

**Comment by pritikin** [comment]
closing this since it was dealt with
